In [1]:
import numpy as np
from src.helpers import load_csv_data, standardize
from src.implementations import least_squares

In [2]:
y, tx, ids = load_csv_data('data/test.csv')

tx, x_mean, x_std = standardize(tx)

In [3]:
from src.polynomials import build_poly_matrix

def polynomial_regression():
    """Constructing the polynomial basis function expansion of the data,
       and then running least squares regression."""
    # define parameters
    degrees = [1, 3, 7]

    for ind, degree in enumerate(degrees):
        
        # Form the data to do polynomial regression
        phi_x = build_poly_matrix(tx, degree)

        print(phi_x[ind])

        # Least square and calculate RMSE
        weights, mse = least_squares(y, phi_x[ind])
        rmse = np.math.sqrt(2 * mse)

        print("Processing {i}th experiment, degree={d}, rmse={loss}".format(
              i=ind + 1, d=degree, loss=rmse))

polynomial_regression()

[2 1 1]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


LinAlgError: Singular matrix